"""AGENTS.md adapter: produces the cross-tool agents.md convention.

AGENTS.md is the emerging open standard used by Codex CLI, OpenCode, and others.
It expects plain markdown with stable H2 sections. We render each section as an
H2 plus body, prefixed with a short provenance block at the top.
"""

from __future__ import annotations

import re

from forge.targets.base import TargetAdapter
from forge.targets.claude_code import _emit_output_frontmatter, _demote_headings
from forge.compiler.section import Section
from forge.compiler.config import Config
from forge.compiler.provenance import build_block, render_markdown_header


class AgentsMdAdapter(TargetAdapter):
    name = "agents-md"
    default_filename = "AGENTS.md"

    def render(self, sections: list[Section], config: Config) -> str:
        parts: list[str] = []
        if config.output_frontmatter:
            parts.append(_emit_output_frontmatter(config.output_frontmatter))
            parts.append("")
        parts.append(f"# {config.name}")
        parts.append("")
        parts.append(
            "> Compiled by forge-core from `sp/section/` + `sp/config/`. "
            "Do not edit this file directly."
        )
        parts.append("")
        parts.append(render_markdown_header(build_block(sections, config), "blockquote"))
        parts.append("")
        if config.preamble.strip():
            parts.append(config.preamble.strip())
            parts.append("")
        for sec in sections:
            parts.append(_heading(sec))
            parts.append("")
            body = sec.body.strip()
            if config.demote_section_headings:
                body = _demote_headings(body)
            parts.append(body)
            parts.append("")
        if config.postamble.strip():
            parts.append(config.postamble.strip())
            parts.append("")
        if config.body.strip():
            parts.append(config.body.strip())
            parts.append("")
        return "\n".join(parts).rstrip() + "\n"


def _heading(sec: Section) -> str:
    pretty = sec.name.replace("-", " ").replace("_", " ").title()
    return f"## {pretty}"
