"""AGENTS.md adapter: produces the cross-tool agents.md convention.

AGENTS.md is the emerging open standard used by Codex CLI, OpenCode, and others.
It expects plain markdown with stable H2 sections. We render each section as an
H2 plus body, prefixed with a short provenance block at the top.
"""

from __future__ import annotations

import re

from forge.targets.base import TargetAdapter
from forge.compiler.section import Section
from forge.compiler.config import Config


class AgentsMdAdapter(TargetAdapter):
    name = "agents-md"
    default_filename = "AGENTS.md"

    def render(self, sections: list[Section], config: Config) -> str:
        parts: list[str] = []
        parts.append(f"# {config.name}")
        parts.append("")
        parts.append(
            "> Compiled by forge-core from `sp/section/` + `sp/config/`. "
            "Do not edit this file directly."
        )
        parts.append("")
        if config.preamble.strip():
            parts.append(config.preamble.strip())
            parts.append("")
        for sec in sections:
            heading = _heading(sec)
            if heading:
                parts.append(heading)
                parts.append("")
            parts.append(sec.body.strip())
            parts.append("")
        if config.postamble.strip():
            parts.append(config.postamble.strip())
            parts.append("")
        if config.body.strip():
            parts.append(config.body.strip())
            parts.append("")
        return "\n".join(parts).rstrip() + "\n"


def _heading(sec: Section) -> str:
    body = sec.body.lstrip()
    first_line = body.splitlines()[0] if body else ""
    if re.match(r"^#{1,2}\s", first_line):
        return ""
    pretty = sec.name.replace("-", " ").replace("_", " ").title()
    return f"## {pretty}"
